name: Test TEAM 30 model for time-domain

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-22.04
    container: dolfinx/dolfinx:vnightly
    steps:
      - uses: actions/checkout@v3
    
      - name: Flake8 code
        run: flake8 .
      
      - name: Mypy check
        run: python3 -m mypy .

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt --user

      - name: Run test
        run: |
          mpirun -n 2 python3 -m pytest -vs test_team30.py
